Staffbase/gha-workflows

.github/release-drafter.yml, .github/workflows/template_release_drafter.yml, .github/workflows/template_stale.yml
```
The workflow is not valid. In .github/workflows/stale.yml (Line: 10, Col: 11): Error from called workflow Staffbase/gha-workflows/.github/workflows/template_stale.yml@v1.0.0 (Line: 15, Col: 18): Unexpected type of value 'true', expected type: Boolean.
```
=> :bug: fix wrong datatype

.github/workflows/cla.yml, .github/workflows/template_autodev.yml, README.md
- add autodev action template
- change allow list so dependabot is able to create PRs good
=> ✨  Add autodev action

.github/workflows/template_sonarcloud.yml, README.md
- add sonarcloud template
- test it with the [following pr](https://github.com/Staffbase/gatekeeper/pull/249)
=> :sparkles: create sonarcloud template

README.md
=> :memo: adjust wording

.github/workflows/cla.yml
=> :art: update cla path

.github/workflows/template_jira_tagging.yml, README.md
- add jira release tagging workflow
- [example pr](https://github.com/Staffbase/backend/pull/6296)
=> :sparkles: add jira tagging workflow (only for staffbase members)

.github/workflows/template_sonarcloud.yml
- add input `args` for sonarcloud template
=> :art: add input args for sonarcloud

README.md
- Added some more information about options to the Readme
- We should make the entrance to using these templates as simple as possible. ;)
=> :wrench: Add some info about options to the Readme

.github/workflows/template_autodev.yml, .github/workflows/template_gitops.yml, .github/workflows/template_jira_tagging.yml, README.md
- use public repos for checking out the action - everybody can use it
- add parameters for `autodev` and `gitops`
=> 🎨  Add parameters and use public repos - actions usable by everyone

.github/workflows/template_autodev.yml
- add check for dependabot in autodev action
=> :art: add check for dependabot in autodev

.github/workflows/template_gitops.yml
- add explicit checkout for gitops action because of the `yq`
=> :rewind: revert direct gitops usage

.github/workflows/versions.yml
- add workflow to update readme versions automatically
=> :construction_worker: add update readme workflow

.github/workflows/template_gitops.yml, README.md
=> CLP-0000: Add "dockerenabled" input to GitOps template

.github/workflows/template_gitops.yml
=> :bug: fix wrong input field

.github/workflows/template_jira_tagging.yml, README.md
=> :art: add jira default name

.github/workflows/template_sonarcloud.yml, README.md
- add `projectBaseDir` parameter
=> 🎨  Add projectBaseDir to sonarcloud template

.github/workflows/template_gitops.yml, README.md
- add optional npm token to pull private npm packages
- rename docker image name
=> :art: improve gitops template

README.md
=> :memo: update npm token description

.github/workflows/template_gitops.yml, .github/workflows/template_jira_tagging.yml, README.md
- bump gitops action
- rename jira variables
=> Bump gitops

.github/workflows/template_autodev.yml, .github/workflows/template_jira_tagging.yml, README.md
- fix required step for jira
- bump autodev
- add optionals in documentation
=> 🎨 Bump AutoDev and fix required jira

.github/workflows/cla.yml, .github/workflows/template_autodev.yml, .github/workflows/template_gitops.yml, .github/workflows/template_jira_tagging.yml, .github/workflows/template_release_drafter.yml, .github/workflows/template_stale.yml, .github/workflows/template_yaml.yml, .github/workflows/versions.yml
- [new ubuntu image is available](https://github.com/actions/virtual-environments/issues/5490#issuecomment-1193393725)
- merge the PR after 8th August then the image is generally available
=> :arrow_up: bump ubuntu image

README.md
=> Update README for secret scan action

README.md
- Updating the jobs uri
- Requested by @philippstorl
=> Update Staffbase jobs uri

.github/workflows/template_techdocs.yml, README.md
This add the https://github.com/Staffbase/backstage-techdocs-action.
=> :sparkles: Added backstage-techdocs action

.github/workflows/template_techdocs.yml, README.md
- bump ubuntu image
- improve techdocs documentation
=> :memo: improve techdocs documentation

.github/workflows/template_autodev.yml, README.md
- remove opened pull request event, because there can't be a label
- remove closed pull request event, because the run is done on master/main
- add check for autodev to run only if push or label was set/removed
=> 🎨 Improve autodev

.github/workflows/template_techdocs.yml, README.md
To make use of release <https://github.com/Staffbase/backstage-techdocs-action/releases/tag/v0.2.0>
=> :sparkles: Update TechDocs action to make use of additional-plugins

.github/workflows/template_autodev.yml, README.md
=> :construction_worker: add closed event

.github/workflows/template_secret_scan.yml
Added trufflehog flag to verify secrets in order to not fail build if secret was invalidated, but is still found.
=> Added flag to verify creds

.github/workflows/template_yaml.yml
update yamllint to 1.1.1
- [] Update documentation
- [x ] Review the [Contributing Guideline](../blob/main/CONTRIBUTING.md) and sign CLA
=> update yamllint to 1.1.1

.github/workflows/template_gitops.yml
=> :arrow_up: bump gitops template

.github/workflows/cla.yml, .github/workflows/template_gitops.yml
Changed the default settings for secret names to match our new internal default
- [] Refactoring
=> Change Secret Name to point to Artifactory as a new default

.github/workflows/template_jira_tagging.yml
add new version https://github.com/Staffbase/github-action-issue-id-collection/releases/tag/v1.1.0
=> update to version 1.1.0 github-action-issue-id-collection

README.md
Added some missing part for the techdoc documentation.
=> Add some missing techdoc paths

README.md
=> :memo: add limitations

.github/workflows/template_techdocs.yml, README.md
There was a mistake in the previous commit, referencing an unknown property.
=> Fix wrong propery name

.github/workflows/template_yaml.yml
Update GHA workflow for the yamllint action to the latest version.
=> Update yamllint Action

.github/workflows/template_stale.yml, README.md
issues should not be stale - take a look at the frontend
=> :art: only stale pull requests

.github/workflows/template_gitops.yml
- bump gitops action - [new release](https://github.com/Staffbase/gitops-github-action/releases/tag/v5.1)
=> :arrow_up: bump gitops action

.github/workflows/template_gitops.yml, .github/workflows/template_secret_scan.yml, README.md
Pass docker secrets to gitops action
=> add possibility to pass docker build secrets to the build step

.github/workflows/template_gitops.yml, README.md
=> :art: Add provenance option

.github/workflows/template_gitops.yml, README.md
- The option is not useful for us, we don't want to skip our Multi Stage Build at a certain time: https://docs.docker.com/engine/reference/commandline/build/#target
=> 🔥 Remove Docker Target Option

.github/workflows/template_gitops.yml, README.md
Reverts Staffbase/gha-workflows#126
=> Revert "🔥 Remove Docker Target Option"

.github/workflows/template_launchdarkly_code_references.yml, README.md
Added a LD code reference action to not copy it again and again.
Example run in a repository: https://github.com/Staffbase/pikasso/actions/runs/5211452487/jobs/9403761390
=> ✨ add LD code references action

.github/workflows/template_autodev.yml
=> Bump autodev action to 1.8.0

.github/workflows/template_autodev.yml
- do not auto-link pull requests
=> :arrow_up: bump patch autodev

README.md
=> :arrow_up: Bump readme version

README.md
Increased version numbers in the README.md
=> 📝 increase version numbers in README.md

.github/workflows/template_autodev.yml, README.md
- possibility to use a Github app for authentication
=> :alembic: Using single autodev action

.github/workflows/template_autodev.yml
=> :arrow_up: bump autodev action

.github/workflows/template_autodev.yml, .github/workflows/template_gitops.yml, .github/workflows/template_jira_tagging.yml, .github/workflows/template_launchdarkly_code_references.yml, .github/workflows/template_release_drafter.yml, .github/workflows/template_secret_scan.yml, .github/workflows/template_stale.yml, .github/workflows/template_techdocs.yml, .github/workflows/template_yaml.yml
- using explicit versions for GitHub actions
- better knowledge about new versions
- constant behavior of the reusable actions
=> :art: Using explicit versions

.github/workflows/template_release_drafter.yml, README.md
- add default release drafter configuration
=> :art: Add default drafter config

.github/workflows/template_autodev.yml, .github/workflows/template_jira_tagging.yml, .github/workflows/template_release_version.yml, .github/workflows/template_secret_scan.yml, README.md
- add new reusable workflow to get next version in format `YEAR.WEEK.COUNTER`
- fetch all tags only if necessary
=> :sparkles: Add next version workflow

.github/workflows/template_release_version.yml
- create new release if there exists no other release
=> :art: Improve next release version

.github/workflows/template_release_drafter.yml, README.md
Reverts Staffbase/gha-workflows#156
default config does not work with release drafter context
=> Revert ":art: Add default drafter config"

.github/workflows/template_release_version.yml
=> :bug: Fix release check

.github/workflows/template_release_version.yml
- improve release check with no git repo
=> :art: Improve release check

.github/workflows/template_gitops.yml, README.md
Add `working-directory` parameter support for [gitops-github-action](https://github.com/Staffbase/gitops-github-action)
=> :sparkles: GitOps: add working-directory parameter

.github/workflows/cla.yml
Add timdittler to CLA allowlist
=> Add timdittler to CLA allowlist

README.md
- adjust cron job trigger for every first day in the year
=> :memo: Adjust version detector cron job

.github/workflows/template_automerge_dependabot.yml
- auto merge works perfectly
- [add auto approving to merge PRs directly](https://cli.github.com/manual/gh_pr_review)
=> :art: Add approval for pull request

README.md
- add hint for version resolver to remove all other release configuration
=> :memo: Update version resolve documentation

.github/workflows/template_automerge_dependabot.yml, README.md
- using GitHub app for auto-merge authentication
- able to run the GitHub action after a merge
=> :art: Using github app for auto merge

.github/workflows/template_testio_trigger_test.yml
New version of https://github.com/Staffbase/testio-trigger-test-github-action contains a bug fix and should be rolled out because instructions about how to use this action is now visible in the PR template of the frontend repo.
=> ⬆️ Bump TestIO version

.github/workflows/template_techdocs.yml
=> CIV-424 Rename Storage Name

.github/workflows/template_release_version.yml, README.md
- add format option to release version detector
=> :art: Add release version format

.github/workflows/template_automerge_dependabot.yml
- improve dependabot check for automated approval
=> :art: Improve dependabot check

.github/workflows/template_release_version.yml
- add check for weekly release to change patch version
=> :bug: Fix quarterly patch version

.github/workflows/template_autodev.yml, .github/workflows/template_automerge_dependabot.yml, .github/workflows/template_release_drafter.yml
Replace tibdex app token action by one from GitHub.
We prefer actions from GH to ones from private people.
=> Replace tibdex app token action by one from GitHub

.github/CODEOWNERS
=> :fire: remove Jan as codeowner

.github/workflows/template_automerge_dependabot.yml
Remove approval from auto-merge workflow. This is not necessary for the process.
=> 🔥 Remove approving from auto-merge workflow

.github/workflows/template_gitops.yml
Version bump
Use Gitops Action v5.5
=> DIA-3549 Version Bump for Gitops Action to enable retagging

.github/workflows/template_gitops.yml, README.md
- add option to disable prod retagging
=> :wrench: Add retagging options

.github/workflows/template_gitops.yml
update gitops action to stabilize cd workflow
tested here: https://github.com/Staffbase/customer-control/actions/runs/10923940115/job/30322108816
=> update gitops action to v6.2

.github/workflows/template_gitops.yml
Reverts Staffbase/gha-workflows#287
=> Revert "chore(deps): bump Staffbase/gitops-github-action from 6.2 to 6.3"

.github/workflows/template_release_drafter.yml, README.md
Support prereleases for release-drafter
=> Support prereleases for release-drafter

.github/workflows/template_terraform_format.yml
Use correct git ref to push changes back
=> 🐛 CIV-812 Use correct git ref to push changes back

.github/workflows/template_release_version.yml
- using correct week number for release version
=> :bug: Fix week number

.github/workflows/template_release_drafter.yml, README.md
=> :art: Add release drafter config name

.github/workflows/template_yaml.yml
Update yamllint GitHub Action
CLA
=> DIA-3557: Update yamllint GitHub Action

.github/workflows/template_gitops.yml, README.md
- add the runs-on property to the gitops template
=> add the runs-on property to the gitops template
