Staffbase/gha-workflows

.github/workflows/template_secret_scan.yml, .github/workflows/trufflehog_secretscan.yml, README.md
=> Reusable Trufflehog Workflow

.github/workflows/template_gitops.yml
Use the new Gitops Action version with Artifactory as the new default.
=> Bump the used gitops action version to v5

.github/workflows/template_techdocs.yml, README.md
This will change the behavior of the techdocs action to publish to Azure Blob storage by default.
Configuration was enhanced to support both publish targets AWS and Azure.
=> Use Azure as default publisher for TechDocs

.github/workflows/template_testio_trigger_test.yml
During development the testio GHA was referenced from the main branch. Since we have a release now https://github.com/Staffbase/testio-trigger-test-github-action/releases/tag/v1.0.0 we should use it
=> ⬆️ set testio action version to v1.0.0 instead of main

.github/workflows/template_automerge_dependabot.yml, README.md
- create dependabot auto-merge action
- tested in own testing environment (see comment)
- ⚠️ using real version in autodev action project
=> :art: Create dependabot automerge action

.github/workflows/template_gitops.yml, README.md
- remove explicit tokens
- usage of one of the docker build secrets properties is recommended
=> :fire: Remove explicit tokens

.github/workflows/template_automerge_dependabot.yml, README.md
=> :art: Force automerge as admin

.github/workflows/template_automerge_dependabot.yml
This PR restricts the condition for performing dependency auto-merge by excluding dependencies with major version 0.
Done to adhere to semantic versioning guidelines, which state that patch and minor bumps in dependencies with major version 0 can potentially contain breaking changes.
https://semver.org/#spec-item-4
=> Disable auto-merge for dependency bumps with major version 0

.github/workflows/template_release_drafter.yml, README.md
- add explicit secrets to release drafter
- add hint for GITHUB_TOKEN limitations
=> 🎨 Extend release drafter

.github/workflows/template_stale.yml
- I thought that the action is already configured so that no issues are staled. However, this is not the case, [which is why I am now actively deactivating the staling of issues](https://github.com/actions/stale?tab=readme-ov-file#days-before-stale). 
- You can still set the stale label manually and the action recognizes the issue as stale and then closes it after the seven days.
=> :memo: Disable staling for issues

.github/workflows/template_automerge_dependabot.yml, README.md
This PR adds a `strategy` option to dependabot automerge workflow.
It allows to select the merge strategy. The possible options are:
- `rebase`
- `merge`
- `squash` (default)
=> Feat: Add strategy selection to dependabot automerge workflow

.github/workflows/template_gitops.yml, README.md
Remove provenance option. I've removed it already from gitops action
https://github.com/Staffbase/gitops-github-action/pull/83
=> CIV-244 Remove provenance option

.github/workflows/template_gitops.yml, README.md
* Support GitHub Apps for GitOps Workflow
=> Support GitHub Apps for GitOps Workflow

.github/workflows/template_gitops.yml, README.md
I added all possible options from the `gitops-action` to the workflow with our defaults. This should be downward compatible and gives us the possibility to remove "our" defaults from the actions themselves.
=> Add all options with our defaults to reusable workflow

.github/workflows/versions.yml
- version bump action does not work because we are using the GITHUB_TOKEN which does not trigger any pipeline
- using custom token, so we can simply merge the version bump PR
=> :construction_worker: Add custom token for PR creation

.github/workflows/template_automerge_dependabot.yml
Reverts Staffbase/gha-workflows#251
Currently all PRs without force power are not merged automatically due to this change.
=> Revert "🔥 Remove approving from auto-merge workflow"

.github/workflows/template_gitops.yml, README.md
Update default gitops-email and gitops-user
=> NO-TICKET Update default gitops-email and gitops-user

.github/workflows/template_automerge_dependabot.yml, README.md
This PR adds 2 inputs to the automerge dependabot workflow:
- `update-types`: Specify which kind of updates you allow to automerge. Possible values are: `minor`, `major`, `patch`. (Default value: `minor,patch`)
- `include-pre-release`: Specify if you want to allow automerge of pre-release, semver starting with `0.`. (Default value: `false`)
=> CLP-0000: Add an input type to specify update types for dependabot automerge workflow

.github/workflows/template_gitops.yml, README.md
- [Emit on dev](https://github.com/Staffbase/casper/actions/runs/11405214766/job/31736166480#step:5:864)
- [Emit on merge](https://github.com/Staffbase/casper/actions/runs/11405254346/job/31736297017#step:5:865)
- [Emit on tag](https://github.com/Staffbase/casper/actions/runs/11405281057/job/31736387903#step:5:580)
=> Emit image build event for upwind

.github/workflows/template_terraform_format.yml, README.md
Add Reusable Workflow for Terraform Format
=> CIV-812 Add Reusable Workflow for Terraform Format
